# Question 15, chapter 3

library(MASS)
names(Boston)
attach(Boston)
lm.zn <- lm(crim ~ zn)
summary(lm.zn)
lm.indus <- lm(crim ~ indus)
summary(lm.indus)
lm.chas = lm(crim~chas) 
summary(lm.chas)
lm.nox = lm(crim~nox)
summary(lm.nox) 
lm.rm = lm(crim~rm)
summary(lm.rm) 
lm.age = lm(crim~age)
summary(lm.age)
lm.dis = lm(crim~dis)
summary(lm.dis)
lm.rad = lm(crim~rad)
summary(lm.rad)
lm.tax = lm(crim~tax)
summary(lm.tax)
lm.ptratio = lm(crim~ptratio)
summary(lm.ptratio)
lm.black = lm(crim~black)
summary(lm.black) 
lm.lstat = lm(crim~lstat)
summary(lm.lstat) 
lm.medv = lm(crim~medv)
summary(lm.medv) 

# Multiple Regression

lm.mult <- lm(crim ~ . , data = Boston)
summary(lm.mult)

#
simple.reg <- vector("numeric", 0)
simple.reg <- c(simple.reg, lm.zn$coefficient[2])
simple.reg <- c(simple.reg, lm.indus$coefficient[2])
simple.reg <- c(simple.reg, lm.chas$coefficient[2])
simple.reg <- c(simple.reg, lm.nox$coefficient[2])
simple.reg <- c(simple.reg, lm.rm$coefficient[2])
simple.reg <- c(simple.reg, lm.age$coefficient[2])
simple.reg <- c(simple.reg, lm.dis$coefficient[2])
simple.reg <- c(simple.reg, lm.rad$coefficient[2])
simple.reg <- c(simple.reg, lm.tax$coefficient[2])
simple.reg <- c(simple.reg, lm.ptratio$coefficient[2])
simple.reg <- c(simple.reg, lm.black$coefficient[2])
simple.reg <- c(simple.reg, lm.lstat$coefficient[2])
simple.reg <- c(simple.reg, lm.medv$coefficient[2])
multiple.reg <- vector("numeric", 0)
multiple.reg <- c(multiple.reg, lm.mult$coefficients[2:length(lm.mult$coefficients)])
plot(simple.reg, multiple.reg)
